name: DISH DAMES
favicon: null
layout_spectrum: 0.9789799442514777
typography_spectrum: 0.17614
title: Dish Dames
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d6d4dc'
    - '#4c4751'
    - '#27222a'
    - '#9f9da6'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
