name: DISH DAMES
favicon: null
layout_spectrum: 0.9789799442514777
typography_spectrum: 0.17614
title: Dish Dames
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#452c4a'
    - '#685c50'
    - '#cf8c72'
    - '#e0c5ba'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
