name: DISH DAMES
favicon: null
layout_spectrum: 0.9789799442514777
typography_spectrum: 0.9192181180696934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5302838340867311
  lightness: 0.08296737563796341
  saturation: 0.9514150922186673
  rhythmicContrast: 0.7784724147059023
purpose: []
